version: '3.4'

x-common-variables: &common-variables
 MINIO_ACCESS_KEY: minio
 MINIO_SECRET_KEY: minio123
 MINIO_URL: minio:9000
 MINIO_BUCKET_NAME: hse-api-bucket
 RESTRICTED_MODE: 0

services:
 hse-api-web:
  build:
   context: .
   dockerfile: hseling_api_generator/Dockerfile
  ports:
   - "5000:80"
  volumes:
   - ./hseling_api_generator/hseling_api_generator:/app/hseling_api_generator
  links:
   - minio
  environment: *common-variables


 minio:
  image: minio/minio:latest
  volumes:
   - data:/data
  ports:
   - "9000:9000"
  command: server /data/minio
  environment: *common-variables

 dev-server:
  build: 
   context: ./hseling_web_generator/
  ports:
   - "8000:80"
  #volumes:
  # - ./hseling_web_generator/src:/opt/code
  depends_on:
   - hse-api-web

volumes:
  data:
